services:
   zbir:
     build:
       context: .
       dockerfile: Dockerfile
       args:
          - USER_ID=${USER_ID}
          - USER_NAME=${USER_NAME}  
          - GROUP_ID=${GROUP_ID}
          - GROUP_NAME=${GROUP_NAME}
     volumes:
       - volume1:/app/data
     stdin_open: true
     tty: true
     image: priprema:v1

volumes:
  volume1:
